### ISSUE TITLE
Error when installing the requirements

### ISSUE THREAD

**Issue by RacheleSprugnoli** [segment-any-text/wtpsplit#122]
Hello!
When installing the requirements (pip install -r requirements.txt) I have the following error (the first of a long list indeed...):

```
Downloading spacy-3.0.6.tar.gz (7.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 10.7 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... error
Error compiling Cython file:
------------------------------------------------------------
...
int length
cdef class Vocab:
cdef Pool mem
cpdef readonly StringStore strings
------------------------------------------------------------
spacy/vocab.pxd:28:10: Variables cannot be declared with 'cpdef'. Use 'cdef' instead.
``` 
Any suggestions on how to solve it?
Thanks in advance,
Rachele

**Comment by bminixhofer** [comment]
FYI you'll only need to install the packages in `requirements.txt` if you're trying to reproduce the baselines from the paper, otherwise the requirements in `setup.py` are enough: https://github.com/segment-any-text/wtpsplit/blob/cfd5e24411d8c658b3000af0c62b6602a6c955ca/setup.py#L10-L21

In case that is what you are trying to do, this seems like an issue with SpaCy, you could try e.g. the solution [here](https://github.com/explosion/spaCy/issues/13449#issuecomment-2101005734) or upgrading SpaCy.
